config/routes.rb
Rails.application.routes.draw do
  resources :group_assignments
  resources :users

  root "static_pages#home"
  post "generate_groups" => "group_assignments#generate_groups"
  post "group_assignments/destroy_all" => "group_assignments#destroy_all"

end

app/models/group_assignment.rb
class GroupAssignment < ActiveRecord::Base
	belongs_to :user
	validates :group, uniqueness: { scope: [:user] }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :group_assignments, -> { order("created_at DESC") }
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_PHONE_REGEX = /(1?[ -.]?\(?\d{3}\)?[ -.]?\d{3}[ -.]?\d{4}[ extension\.]*\d{0,5})/i
  validates :phone, length: { maximum: 50 }, allow_blank: true,
                    format: { with: VALID_PHONE_REGEX, message: "format is invalid"  },
                    :on => :update
  validates_uniqueness_of :phone
  before_validation :format_phone
  default_scope{order(last_name: :asc)} 

  def first_name=(s)
    write_attribute(:first_name, s.to_s.titleize) # The to_s is in case you get nil/non-string
  end
  
  def last_name=(s)
    write_attribute(:last_name, s.to_s.titleize) # The to_s is in case you get nil/non-string
  end
  #strip non-numerical characters from phone number
  def format_phone
    if @phone != nil
      @phone = self.phone.scan(/[0-9]/).join
      self.phone = @phone.length == 7 ? ActionController::Base.helpers.number_to_phone(@phone) : 
      @phone.length == 10 ? ActionController::Base.helpers.number_to_phone(@phone, area_code: true) :
      @phone

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/group_assignments_controller.rb
class GroupAssignmentsController < ApplicationController
  before_action :set_group_assignment, only: [:show, :edit, :update, :destroy]

  def generate_groups
    GroupAssignment.delete_all
    num_of_users = User.where(active:true).count
    if num_of_users >= 3
      num_of_groups = num_of_users / 3
      num_of_extras = num_of_users % 3
      groups = []
      (1..num_of_groups).each do |group|
        groups = groups + ([group] * 3)
        if num_of_extras > 0
          groups.push(group)
          num_of_extras -= 1
        end
        if group == num_of_groups
          until num_of_extras <= 0 do
            groups.push(group)
            num_of_extras -= 1
          end
        end
      end
      puts groups
      groups = groups.shuffle
      puts groups
      User.where(:active => true).entries.each do |user|
        group = groups.pop
        @group_assignment = GroupAssignment.new(user: user, group: group)
        if @group_assignment.save
          flash[:notice] = "Group successfully generated."
        else
          flash[:error] = "Sorry, a group could not be saved."
        end
      end
    else
      flash[:error] = "Sorry, there are not enough users to create groups"
    end
    redirect_to action: "index"
  end

  # GET /group_assignments
  # GET /group_assignments.json
  def index
    @group_assignments = GroupAssignment.all.joins(:user)
      .order('group_assignments.group ASC, users.last_name ASC')
  end

  # GET /group_assignments/1
  # GET /group_assignments/1.json
  def show
  end

  # GET /group_assignments/new
  def new
    @group_assignment = GroupAssignment.new
  end

  # GET /group_assignments/1/edit
  def edit
  end

  # POST /group_assignments
  # POST /group_assignments.json
  def create
    @group_assignment = GroupAssignment.new(group_assignment_params)

    respond_to do |format|
      if @group_assignment.save
        format.html { redirect_to @group_assignment, notice: 'Group assignment was successfully created.' }
        format.json { render :show, status: :created, location: @group_assignment }
      else
        format.html { render :new }
        format.json { render json: @group_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_assignments/1
  # PATCH/PUT /group_assignments/1.json
  def update
    respond_to do |format|
      if @group_assignment.update(group_assignment_params)
        format.html { redirect_to @group_assignment, notice: 'Group assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_assignment }
      else
        format.html { render :edit }
        format.json { render json: @group_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_assignments/1
  # DELETE /group_assignments/1.json
  def destroy
    
    respond_to do |format|
      format.html { redirect_to group_assignments_url, notice: 'Group assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_assignment
      @group_assignment = GroupAssignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_assignment_params
      params.require(:group_assignment).permit(:user, :group)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :phone, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_assignments_helper.rb
module GroupAssignmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/group_assignments/_form.html.erb
<%= form_for(@group_assignment) do |f| %>
  <% if @group_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_assignment.errors.count, "error") %> prohibited this group_assignment from being saved:</h2>

      <ul>
      <% @group_assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_assignments/edit.html.erb
<h1>Editing Group Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_assignment %> |
<%= link_to 'Back', group_assignments_path %>

app/views/group_assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lunch Group Assignments</h1>

    <% if @group_assignments.count == 0 %>
      <div>
        No groups
      </div>
    <% else %>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_assignments.each do |group_assignment| %>
      <tr>
        <td><%= group_assignment.user.first_name %> <%= group_assignment.user.last_name %></td>
        <td><%= group_assignment.group %></td>
        <td><%= link_to 'Show', group_assignment %></td>
        <td><%= link_to 'Edit', edit_group_assignment_path(group_assignment) %></td>
        <td><%= link_to 'Destroy', group_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

    <% end %>
<br>

<%= button_to "Generate New Groups", generate_groups_path %>

app/views/group_assignments/new.html.erb
<h1>New Group Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', group_assignments_path %>

app/views/group_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @group_assignment.user %>
</p>

<p>
  <strong>Group:</strong>
  <%= @group_assignment.group %>
</p>


<%= link_to 'Edit', edit_group_assignment_path(@group_assignment) %> |
<%= link_to 'Back', group_assignments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FamilyFridays</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="menu-item">
	<li>
		<%= link_to 'Users', users_path %>
	</li>
	<li>
		<%= link_to 'Groups', group_assignments_path %>
	</li>
	<li>
		<%= link_to 'Home', root_path %>
	</li>
</ul>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<div class="home">
	<h1>
		Welcome to Family Fridays
	</h1>
	<div id="page">
	  <% if flash[:alert] %>
	    <p class="flash-error">Error:<%= flash[:error] %></p>
	  <% end %>
	  <% if flash[:notice] %>
	    <p class="flash-notice">Warning:<%= flash[:notice] %></p>
	  <% end %>
	  <%= yield %>
	</div>
	<div>
		<div>Step 1: Tell us who is joining by adding them to the users list.</div>
		<div><%= link_to 'Users', users_path %></div>
	</div>
	<div>
		<div>Step 2: Generate your Friday lunch group by clicking the button below.</div>
		<div><%= button_to "Generate Groups", generate_groups_path %></div>
	</div>
	<div>
		<div>Step 3: Visit the groups page any time, to see what the assignments were. </div>
		<div><%= link_to 'Groups', group_assignments_path %></div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phone %></td>
        <td><%= user.active %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>